### ISSUE TITLE
1.19.2 Crashes

### ISSUE THREAD

**Issue by shaffera777** [gigaherz/SewingKit#11]
Crash when accessing the sewing table.
[crash-2022-08-08_20.54.50-client.txt](https://github.com/gigaherz/SewingKit/files/9286132/crash-2022-08-08_20.54.50-client.txt)

**Comment by gigaherz** [comment]
Huh, I'll look into it.

**Comment by gigaherz** [comment]
Oops! Found the bug. Was something silly as expected.

![image](https://user-images.githubusercontent.com/685851/183655109-599f14ba-9e72-46be-8f2b-1f27f264a408.png)

Everything works now :D

**Comment by gigaherz** [comment]
Should be fixed as of 1.6.6
