### ISSUE TITLE
Tailor villager has no Zombie texture

### ISSUE THREAD

**Issue by brisingraerowing** [gigaherz/SewingKit#4]
This results in a missing texture zombie with the farmer model.

![2021-03-26_19 47 20](https://user-images.githubusercontent.com/250409/112703095-1f705600-8e6c-11eb-8afc-9711f642ac31.png)

(I used a 'net' from the Mob Catcher mod to identify the profession by viewing the NBT).

**Comment by gigaherz** [comment]
Oh, I completely forgot zombie villagers are a thing that exists, when making the texture!

**Comment by RedBeast1959** [comment]
![2022-08-10_21 52 42](https://user-images.githubusercontent.com/100399264/183907026-5d02c9f9-d3b1-46d8-9254-a895a2238ae9.png)

Same problem in 1.19.2 version.

**Comment by gigaherz** [comment]
Oh crap this issue completely slipped my mind.

**Comment by gigaherz** [comment]
Fixed in version 1.7.1 for 1.19.2.
