### ISSUE TITLE
Sewing Table With Drawers has no drawers

### ISSUE THREAD

**Issue by HopsandBarley** [gigaherz/SewingKit#5]
The GUI for the Sewing Table with Drawers is the same as the GUI for the Sewing table.  There is no storage.

![image](https://user-images.githubusercontent.com/78277756/131549419-d0a17d51-c977-4f3e-bbff-583e8906a0ba.png)

![image](https://user-images.githubusercontent.com/78277756/131549476-5fc7428e-317d-49e7-800f-6c63f1e10f2a.png)

**Comment by gigaherz** [comment]
The Storing Sewing Table keeps the items when closed, the normal one does not.
That's the difference.

**Comment by HopsandBarley** [comment]
ah, i did not realize that.  Thanks for the clarification.
