### ISSUE TITLE
[1.18.2] Too many mods in a single pack stops toolbelt recipe from registering.

### ISSUE THREAD

**Issue by Baggytrousers27** [gigaherz/SewingKit#9]
Not sure if it's too many mods or one specific mod (narrowing down while typing this) but jei won't show a recipe for the Toolbelt (from your other mod). Will get back to you with more info soon.

**Comment by gigaherz** [comment]
Can you provide a log file? If there's a loading error it should appear in the latest.log

**Comment by Baggytrousers27** [comment]
_[09May2022 14:08:38.800] [Server thread/INFO] [net.minecraft.world.item.crafting.RecipeManager/]: Skipping loading recipe toolbelt:belt_via_sewing as it's serializer returned null_
From
[Latest.log](https://gist.github.com/Baggytrousers27/6f28c2f769a62d130113b510f2768ab1)
Let me know if debug is needed as well.

**Comment by gigaherz** [comment]
That line is harmless. It means the recipe was disabled.

you should look a few lines down: 
```
[09May2022 14:07:56.205] [Render thread/ERROR] [net.minecraft.world.item.crafting.RecipeManager/]: Parsing error loading recipe mysticalagriculture:essence/chisel/limestone
com.google.gson.JsonSyntaxException: Unknown item 'chisel:limestone/raw'
```
It's an issue in chisel, not sewing kit.

**Comment by gigaherz** [comment]
Err, not chisel, mystical agriculture, which seems to require chisel

**Comment by gigaherz** [comment]
Wait scratch that. I looked too quickly and did a brainfart.
The other recipe errors are annoying but not the issue.
The issue is that Tool Belt thinks Sewing Kit is not present or disabled.

**Comment by gigaherz** [comment]
OOPS I found a bug in the config.

```
            enableSewingKitSupport = builder
                    .comment("If set to FALSE, support for sewing recipes will not be enabled regardless of the mod's presence.")
                    .translation("text.toolbelt.config.disable_anvil_update")
                    .define("disableAnvilUpgrading", false);
```

There's a config value that I forgot to rename, "disableAnvilUpgrading" should really be called "enableSewingKitSupport". If you set that to false, set it to true.

**Comment by Baggytrousers27** [comment]
That worked. Thanking you muchly. ¦D
